package com.hostel.backend.enums;

public enum AuditAction {
    USER_LOGIN,
    USER_LOGOUT,
    PASSWORD_CHANGE,
    STUDENT_CREATED,
    STUDENT_UPDATED,
    STUDENT_DELETED,
    ROOM_CREATED,
    ROOM_UPDATED,
    ROOM_DELETED,
    ROOM_ALLOCATED,
    ROOM_VACATED,
    COMPLAINT_RAISED,
    COMPLAINT_UPDATED,
    COMPLAINT_RESOLVED,
    PAYMENT_RECEIVED,
    BILL_GENERATED,
    MEAL_CANCELLED,
    SETTING_UPDATED,
    ADMISSION_SUBMITTED,
    ADMISSION_UPDATED,
    ADMISSION_APPROVED,
    ADMISSION_REJECTED
}
